{
 "title": "Common",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "frontend,history,matching,worker"
   }
  ]
 },
 "panels": [
  { "title": "Service - $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(service_requests{type=~\"$Service\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (irate(service_errors{type=~\"$Service\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(service_requests{type=~\"$Service\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(service_errors_entity_not_found{type=~\"$Service\"}[5m]))",
     "legendFormat": "Entity Not Found"
    },
    {
     "expr": "sum(irate(service_errors_execution_already_started{type=~\"$Service\"}[5m]))",
     "legendFormat": "Execution Already Started"
    },
    {
     "expr": "sum(irate(service_errors_resource_exhausted{type=~\"$Service\"}[5m]))",
     "legendFormat": "Resource Exhausted"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(service_latency_bucket{type=~\"$Service\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request Vs Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(persistence_requests{type=~\"$Service\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (irate(persistence_errors{type=~\"$Service\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(persistence_requests{type=\"frontend\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(persistence_latency_bucket{type=\"frontend\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "History Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(client_requests{type=\"frontend\", service_role=\"history\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(client_errors{type=\"frontend\", service_role=\"history\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(client_requests{type=\"frontend\", service_role=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(client_errors{type=\"frontend\", service_role=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(client_latency_bucket{type=\"frontend\", service_role=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Matching Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(client_requests{type=\"frontend\", service_role=\"matching\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(client_errors{type=\"frontend\", service_role=\"matching\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(client_requests{type=\"frontend\", service_role=\"matching\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(client_errors{type=\"frontend\", service_role=\"matching\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(client_latency_bucket{type=\"frontend\", service_role=\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}