{
 "title": "History",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "History Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(service_requests{type=\"history\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (irate(service_errors{type=\"history\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(service_requests{type=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(service_errors_entity_not_found{type=\"history\"}[5m]))",
     "legendFormat": "Entity Not Found"
    },
    {
     "expr": "sum(irate(service_errors_execution_already_started{type=\"hisotry\"}[5m]))",
     "legendFormat": "Execution Already Started"
    },
    {
     "expr": "sum(irate(service_errors_resource_exhausted{type=\"history\"}[5m]))",
     "legendFormat": "Resource Exhausted"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(service_latency_bucket{type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Transfer Tasks Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Active Transfer Task Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(task_requests{operation=~\"TransferActive.*\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(task_errors{operation=~\"TransferActive.*\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Active Transfer Task By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(task_requests{operation=~\"TransferActive.*\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Transfer Task Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(task_errors{operation=~\"TransferActive.*\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Transfer Errors Breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(task_errors_discarded{operation=~\"TransferActive.*\"}[5m]))",
     "legendFormat": "discarded"
    },
    {
     "expr": "sum (irate(task_errors_limit_exceeded_counter{operation=~\"TransferActive.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Active Transfer Task Processing Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(task_latency_processing_bucket{operation=~\"TransferActive.*\", type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Transfer Task Total Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(task_latency_bucket{operation=~\"TransferActive.*\", type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Transfer Task Queue Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(task_latency_queue_bucket{operation=~\"TransferActive.*\", type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Transfer Task Attempt Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(irate(task_attempt_bucket{operation=\"TransferActiveTaskCommand\", type=\"history\"}[5m])) by (le)"
    }
   ]
  },
  { "title": "Timer Tasks Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Active Timer Task Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(task_requests{operation=~\"TimerActive.*\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(task_errors{operation=~\"TimerActive.*\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Active Timer Task By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(task_requests{operation=~\"TimerActive.*\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Timer Task Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(task_errors{operation=~\"TimerActive.*\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Timer Errors Breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(task_errors_discarded{operation=~\"TimerActive.*\"}[5m]))",
     "legendFormat": "discarded"
    },
    {
     "expr": "sum (irate(task_errors_limit_exceeded_counter{operation=~\"TimerActive.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Active Timer Task Processing Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(task_latency_processing_bucket{operation=~\"TimerActive.*\", type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Timer Task Total Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(task_latency_bucket{operation=~\"TimerActive.*\", type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Timer Task Queue Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(task_latency_queue_bucket{operation=~\"TimerActive.*\", type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Active Timer Task Attempt Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(irate(task_attempt_bucket{operation=\"TimerActiveTaskCommand\", type=\"history\"}[5m])) by (le)"
    }
   ]
  },
  { "title": "Mutable State Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Mutable State Cache Requests By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation)(irate(cache_requests{cache_type=\"mutablestate\"}[5m]))",
     "legendFormat": "{{operation}} - requests"
    }
   ]
  },
  {
   "title": "Mutable State Cache Miss By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation)(irate(cache_miss{cache_type=\"mutablestate\"}[5m]))",
     "legendFormat": "{{operation}} - cache_miss"
    }
   ]
  },
  {
   "title": "Mutable State Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cache_requests{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
     "legendFormat": "cache_requests"
    },
    {
     "expr": "sum(irate(cache_errors{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
     "legendFormat": "cache_failures"
    },
    {
     "expr": "sum(irate(cache_miss{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
     "legendFormat": "cache_miss"
    },
    {
     "expr": "sum(irate(acquire_lock_failed{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
     "legendFormat": "acquire_lock_failed"
    }
   ]
  },
  {
   "title": "Mutable State Cache Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(cache_latency_bucket{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Mutable State Load Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cache_requests{cache_type=\"mutablestate\", operation=\"HistoryCacheGetCurrentExecution\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(cache_errors{cache_type=\"mutablestate\", operation=\"HistoryCacheGetCurrentExecution\"}[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Mutable State Load Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(cache_latency_bucket{cache_type=\"mutablestate\", operation=\"HistoryCacheGetCurrentExecution\"}[5m])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "GetOrCreate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cache_requests{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
     "legendFormat": "cache_requests"
    },
    {
     "expr": "sum(irate(cache_errors{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
     "legendFormat": "cache_errors"
    },
    {
     "expr": "sum(irate(cache_miss{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
     "legendFormat": "cache_miss"
    },
    {
     "expr": "sum(irate(acquire_lock_failed{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
     "legendFormat": "acquire_lock_failed"
    }
   ]
  },
  {
   "title": "GetOrCreateCurrent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cache_requests{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
     "legendFormat": "cache_requests"
    },
    {
     "expr": "sum(irate(cache_errors{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
     "legendFormat": "cache_errors"
    },
    {
     "expr": "sum(irate(cache_miss{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
     "legendFormat": "cache_miss"
    },
    {
     "expr": "sum(irate(acquire_lock_failed{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
     "legendFormat": "acquire_lock_failed"
    }
   ]
  },
  { "title": "Events Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Events Cache - Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation)(irate(cache_requests{cache_type=\"events\"}[5m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (operation) (irate(cache_miss{cache_type=\"events\"}[5m]))",
     "legendFormat": "{{ operation }} - cache_miss"
    }
   ]
  },
  {
   "title": "Get Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation)(irate(cache_requests{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum by (operation)(irate(cache_miss{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m]))",
     "legendFormat": "cache_miss"
    },
    {
     "expr": "sum by (operation)(irate(cache_errors{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Get Events Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(cache_latency_bucket{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Put Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cache_requests{cache_type=\"events\", operation=\"EventsCachePutEvent\"}[5m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Put Events Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(cache_latency_bucket{cache_type=\"events\", operation=\"EventsCachePutEvent\"}[5m])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Get Events From Store",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cache_requests{cache_type=\"events\", operation=\"EventsCacheGetFromStore\"}[5m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Get Events From Store Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(cache_latency_bucket{cache_type=\"events\", operation=\"EventsCacheGetFromStore\"}[5m])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "Workflow Task Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "Workflow Task Break Down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(schedule_activity_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "schedule_activity"
    },
    {
     "expr": "sum(irate(complete_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "complete_workflow"
    },
    {
     "expr": "sum(irate(fail_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "fail_workflow"
    },
    {
     "expr": "sum(irate(cancel_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "cancel_workflow"
    },
    {
     "expr": "sum(irate(start_timer_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "start_timer"
    },
    {
     "expr": "sum(irate(cancel_activity_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "cancel_activity"
    },
    {
     "expr": "sum(irate(cancel_timer_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "cancel_timer"
    },
    {
     "expr": "sum(irate(record_marker_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "record_marker"
    },
    {
     "expr": "sum(irate(cancel_external_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "cancel_external_workflow"
    },
    {
     "expr": "sum(irate(continue_as_new_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "continue_as_new"
    },
    {
     "expr": "sum(irate(signal_external_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "signal_external_workflow"
    },
    {
     "expr": "sum(irate(upsert_workflow_search_attributes_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "upsert_searchable_attributes"
    },
    {
     "expr": "sum(irate(child_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "child_workflow"
    }
   ]
  },
  {
   "title": "Sticky Vs Non Sticky",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(service_requests{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "commands_complete"
    },
    {
     "expr": "sum(irate(complete_workflow_task_sticky_enabled_count{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "sticky_tasks"
    },
    {
     "expr": "sum(irate(complete_workflow_task_sticky_disabled_count{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "non_sticky_tasks"
    }
   ]
  },
  {
   "title": "Failed Workflow Task",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(failed_workflow_tasks{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Empty Workflow Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(empty_completion_commands{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "empty_decision"
    }
   ]
  },
  {
   "title": "Multiple Complete Workflows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(multiple_completion_commands{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
     "legendFormat": "empty_workflow"
    }
   ]
  },
  { "title": "Mutable State Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Stale Mutable State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(stale_mutable_state{type=\"history\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  { "title": "Shard Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "Acquire Shards Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(acquire_shards_count[5m]))",
     "legendFormat": "acquire"
    }
   ]
  },
  {
   "title": "Acquire Shards Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(acquire_shards_latency_bucket{type=\"history\"}[5m])) by (le))",
     "legendFormat": "acquire_latency"
    }
   ]
  },
  {
   "title": "Shards Closed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(shard_closed_count[5m]))",
     "legendFormat": "shards_closed"
    }
   ]
  },
  {
   "title": "Shard Item Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sharditem_created_count[5m]))",
     "legendFormat": "item_created"
    },
    {
     "expr": "sum(irate(sharditem_removed_count[5m]))",
     "legendFormat": "item_removed"
    }
   ]
  },
  {
   "title": "Shard Item Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(sharditem_acquisition_latency{type=\"history\"}[5m])) by (le))",
     "legendFormat": "acquire_latency"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Request Vs Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(persistence_requests{type=\"history\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (irate(persistence_errors{type=\"history\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(persistence_requests{type=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 211 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(persistence_latency_bucket{type=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Kafka Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 221 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 222 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(client_requests{type=\"history\", operation=\"MessagingClientPublish\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(client_errors{type=\"history\", operation=\"MessagingClientPublish\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Publish Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 222 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(client_latency_bucket{type=\"history\", operation=\"MessagingClientPublish\"}[5m])) by (le))",
     "legendFormat": "publish_latency"
    }
   ]
  }
 ]
}