{
 "title": "Matching",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Matching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(service_requests{type=\"matching\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (irate(service_errors{type=\"matching\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(service_requests{type=\"matching\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(service_errors_entity_not_found{type=\"matching\"}[5m]))",
     "legendFormat": "Entity Not Found"
    },
    {
     "expr": "sum(irate(service_errors_execution_already_started{type=\"matching\"}[5m]))",
     "legendFormat": "Execution Already Started"
    },
    {
     "expr": "sum(irate(service_errors_resource_exhausted{type=\"matching\"}[5m]))",
     "legendFormat": "Resource Exhausted"
    },
    {
     "expr": "sum by (__name__) (irate({__name__=~\"service_errors_.*\", type=\"matching\"}[5m]))",
     "legendFormat": "{{ $__name__ }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(service_latency_bucket{type=\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Polls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(irate(poll_success[5m]))", "legendFormat": "Success" },
    { "expr": "sum(irate(poll_timeouts[5m]))", "legendFormat": "Timeouts" },
    {
     "expr": "sum(irate(poll_success_sync[5m]))",
     "legendFormat": "Sync Matches"
    }
   ]
  },
  {
   "title": "Throttled Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(sync_throttle_count[5m]))",
     "legendFormat": "Throttle"
    }
   ]
  },
  {
   "title": "Sync Match - Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(syncmatch_latency_bucket{type=~\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "sync - {{operation}}"
    },
    {}
   ]
  },
  {
   "title": "Async Match - Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(asyncmatch_latency_bucket{type=~\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    },
    {}
   ]
  },
  {
   "title": "Forwarded Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(irate(forwarded[5m]))", "legendFormat": "forwarded_api_calls" }
   ]
  },
  {
   "title": "Local To Local Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(local_to_local_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Local To Remote Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(local_to_remote_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Remote To Local Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(remote_to_local_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Remote To Remote Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(remote_to_remote_matches[5m])) ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Tasklist Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Lease Request Vs Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(irate(lease_requests[5m]))", "legendFormat": "requests" },
    { "expr": "sum(irate(lease_failures[5m]))", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Expired Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(irate(tasks_expired[5m]))", "legendFormat": "expired_tasks" }
   ]
  },
  {
   "title": "Throttle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sync_throttle_count[5m]))",
     "legendFormat": "sync_throttle"
    },
    {
     "expr": "sum(irate(buffer_throttle_count[5m]))",
     "legendFormat": "buffer_throttle"
    }
   ]
  },
  {
   "title": "Error Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(condition_failed_errors[5m]))",
     "legendFormat": "condition_failed"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Request Vs Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(persistence_requests{type=\"matching\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (irate(persistence_errors{type=\"matching\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(persistence_requests{type=\"matching\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "e", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(persistence_latency_bucket{type=\"matching\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "History Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(client_requests{type=\"matching\", service_role=\"history\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(client_errors{type=\"matching\", service_role=\"history\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(client_requests{type=\"matching\", service_role=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (irate(client_errors{type=\"matching\", service_role=\"history\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(client_latency_bucket{type=\"matching\", service_role=\"history\"}[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}