{
 "title": "Temporal",
 "description": "Landing dashboard for Temporal",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "frontend,history,matching,worker"
   },
   { "name": "Client", "query": "frontend,history,matching" }
  ]
 },
 "panels": [
  {
   "title": "Workflow Completion Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Completion Overview",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(workflow_success{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(irate(workflow_failed{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(irate(workflow_timeout{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "timedout"
      },
      {
       "expr": "sum(irate(workflow_terminate{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "terminate"
      },
      {
       "expr": "sum(irate(workflow_cancel{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "cancelled"
      }
     ]
    },
    {
     "title": "Workflow Success By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (irate(workflow_success{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Failed By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (irate(workflow_failed{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Timedout By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (irate(workflow_timeout{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Terminate By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (irate(workflow_terminate{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Cancelled By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (irate(workflow_cancel{type=\"history\", operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ namespace }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Overview - $Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service RequestsVs Errors ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (irate(service_requests{type=~\"$Service\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (irate(service_errors{type=~\"$Service\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Service Requests Per Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (irate(service_requests{type=~\"$Service\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Service Errors Break Down ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(service_errors_entity_not_found{type=~\"$Service\"}[5m]))",
       "legendFormat": "Entity Not Found"
      },
      {
       "expr": "sum(irate(service_errors_execution_already_started{type=~\"$Service\"}[5m]))",
       "legendFormat": "Execution Already Started"
      },
      {
       "expr": "sum(irate(service_errors_resource_exhausted{type=~\"$Service\"}[5m]))",
       "legendFormat": "Resource Exhausted"
      }
     ]
    },
    {
     "title": "Service Errors By Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (irate(service_errors{type=~\"$Service\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Service Latency ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(irate(service_latency_bucket{type=~\"$Service\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Client - $Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Vs Errors ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(client_requests{type=~\"$Service\", service_role=~\"$Client\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(irate(client_errors{type=~\"$Service\", service_role=~\"$Client\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Client Requests Per Operation ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (irate(client_requests{type=~\"$Service\", service_role=~\"$Client\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors By Operation ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (irate(client_errors{type=~\"$Service\", service_role=~\"$Client\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Client Latency ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(irate(client_latency_bucket{type=~\"$Service\", service_role=~\"$Client\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence - $Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistence Requests Vs Errors ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (irate(persistence_requests{type=~\"$Service\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (irate(persistence_errors{type=~\"$Service\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Persistence Requests Per Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum by (operation) (irate(persistence_requests{type=~\"$Service\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Persistence Errors By Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (irate(persistence_errors{type=~\"$Service\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Persistence Latency ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(irate(persistence_latency_bucket{type=~\"$Service\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temporal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Availability (Based on Frontend Calls)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - (sum(irate(service_errors{type=\"frontend\"}[2m])) / sum(irate(service_requests{type=\"frontend\"}[2m])) * 100)",
       "legendFormat": "availability"
      }
     ]
    },
    {
     "title": "Persistence Availability",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - (sum (irate(persistence_errors[2m])) /sum (irate(persistence_requests[2m])) * 100)",
       "legendFormat": "availability"
      }
     ]
    },
    {
     "title": "External Events",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (irate(service_requests{operation=~\"StartWorkflowExecution|SignalWorkflowExecution|SignalWithStartWorkflowExecution\", type=\"frontend\"}[2m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Workflow Tasks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(service_requests{type=\"matching\", operation=\"AddWorkflowTask\"}[2m]))",
       "legendFormat": "Scheduled"
      },
      {
       "expr": "sum(irate(service_requests{type=\"history\", operation=\"RecordWorkflowTaskStarted\"}[2m]))",
       "legendFormat": "Started"
      },
      {
       "expr": "sum(irate(service_requests{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[2m]))",
       "legendFormat": "Completed"
      },
      {
       "expr": "sum(irate(service_requests{type=\"history\", operation=\"RespondWorkflowTaskFailed\"}[2m]))",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(irate(schedule_to_start_timeout{type=\"history\", operation=\"TimerActiveTaskWorkflowTimeout\"}[2m]))",
       "legendFormat": "Sticky Task Queue Timeout"
      },
      {
       "expr": "sum(irate(start_to_close_timeout{type=\"history\", operation=\"TimerActiveTaskWorkflowTimeout\"}[2m]))",
       "legendFormat": "Workflow Task Timeout"
      }
     ]
    },
    {
     "title": "Activities",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(service_requests{type=\"matching\", operation=\"AddActivityTask\"}[2m]))",
       "legendFormat": "Scheduled"
      },
      {
       "expr": "sum(irate(service_requests{type=\"history\", operation=\"RecordActivityTaskStarted\"}[2m]))",
       "legendFormat": "Started"
      },
      {
       "expr": "sum(irate(service_requests{type=\"history\", operation=~\"RespondActivityTaskCompleted|RespondActivityTaskFailed|RespondActivityTaskCanceled\"}[2m]))",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Shard Rebalancing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(membership_changed_count[2m]))",
       "legendFormat": "membership_changed"
      },
      {
       "expr": "sum(irate(sharditem_created_count[2m]))",
       "legendFormat": "shard_item_created"
      },
      {
       "expr": "sum(irate(sharditem_removed_count[2m]))",
       "legendFormat": "shard_item_removed"
      },
      {
       "expr": "sum(irate(shard_closed_count[2m]))",
       "legendFormat": "shard_closed"
      }
     ]
    },
    {
     "title": "Shard Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "numshards_gauge", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Restarts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum by (type) (restarts)", "legendFormat": "{{ type }}" }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "num_goroutines", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "GC Counter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(memory_num_gc[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Pause",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(irate(memory_gc_pause_ms_bucket[5m])) by (instance, le))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "memory_stack", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Memory Allocated",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "memory_allocated", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Memory Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "memory_heap", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  }
 ]
}